version: "3.7"

services:
  web:
    build: .
    image: junior-test-app-starterkit
    container_name: junior-test-app-starterkit
    restart: always
    ports:
      - 80:80
    logging:
      options:
        max-size: "100m"
        max-file: "3"
